namespace: animal-adoption

# Default values for the Helm chart
database:
  image: harperdb/harperdb
  username: root
  password: password
  httpThreads: 4
  ports:
    adminLocalPort: 9926
    adminDockerPort: 9926
    userLocalPort: 9925
    userDockerPort: 9925

web:
  image:
    repository: fwmarkcheung/camunda-animal-adoption-app
    tag: latest
  ports:
    localPort: 8080
    dockerPort: 8080
  service:
    port: 8080
  environment:
    SPRING_APPLICATION_JSON: |
      {
          "harperDB.uri": "http://${ANIMAL_ADOPTION_APP_DATABASE_SERVICE_HOST}:${ANIMAL_ADOPTION_APP_DATABASE_SERVICE_PORT_USER}",
          "harperDB.username": "root",
          "harperDB.password": "password"
      }
ingress:
  enabled: true
  host: localhost  # Replace with your domain or IP

