apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    # Uncomment the line below if using a TLS/SSL certificate
    # cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-web
                port:
                  number: {{ .Values.web.service.port }}
  # Uncomment below for HTTPS/TLS setup
  # tls:
  #   - hosts:
  #       - {{ .Values.ingress.host }}
  #     secretName: {{ .Release.Name }}-tls
