# Default values for the Helm chart
database:
  image: harperdb/harperdb
  username: root
  password: password
  httpThreads: 4
  ports:
    adminLocalPort: 9926
    adminDockerPort: 9926
    userLocalPort: 9925
    userDockerPort: 9925

web:
  image:
    repository: animal-adoption-app
    tag: latest
  ports:
    localPort: 8080
    dockerPort: 8080
  environment:
    harperDB:
      uri: "http://database:9925"
      username: root
      password: password
